### PR TITLE
Removes alias_method_chain

### PR DESCRIPTION
**Pull request by RandieM**
Removes alias_method_chain to make compatible with Rails 5.1.2

### CODE REVIEW

**Comment by moggyboy** [comment]
Thanks @RandieM - I wish I had the power to merge this

**Comment by steve-cmi** [comment]
Any word on this? Seems like a simple enough fix.

**Comment by scottbarrow** [comment]
👍 Would like to see this merged

**Comment by lunaru** [comment]
@curtis Hey Curtis, I know this project hasn't been maintained in a while, but it would be awesome to see this PR merged.

**Comment by curtis** [comment]
@RandieM thanks for your pull request!

**Comment by RandieM** [comment]
Great! Glad to see some updates on the gem.

**Pull request merged**
